### ISSUE TITLE
用spring 4.2.5下面的引入报错。

### ISSUE THREAD

**Issue by wzjin** [eryanwcp/essm#1]
用spring 4.2.5下面的引入报错。
类com.eryansky.common.orm.jdbc.SimpleJdbcDao;
引入import org.springframework.jdbc.core.simple.ParameterizedBeanPropertyRowMapper

类com.eryansky.common.web.springmvc;
引入com.eryansky.common.utils.reflection.BeanUtils

**Comment by eryanwcp** [comment]
换成 BeanPropertyRowMapper
